name = "frithhilton-ssr-worker" # Unique name for your Worker
main = "worker.js" # Entry point file
compatibility_date = "2025-09-17" # Current date
usage_model = "bundled" # Suitable for small Workers like this

[site]
bucket = "" # Empty, as assets are served by GitHub Pages, not Worker

# Routes to intercept song pages
[[routes]]
pattern = "www.frithhilton.com.ng/pages/freshPlayer.html*"
zone_name = "frithhilton.com.ng"
