name = "frithhilton-ssr-worker"
main = "worker.js"
compatibility_date = "2025-09-18"

[env.production]
name = "frithhilton-ssr-worker-production"

  [[env.production.routes]]
  pattern = "www.frithhilton.com.ng/pages/freshPlayer.html*"
  zone_name = "frithhilton.com.ng"
