name = "frithhilton-ssr-worker"  # Unique name for your Worker
main = "worker.js"  # Matches your Worker script file
compatibility_date = "2025-09-18"  # Current date

[[routes]]
pattern = "www.frithhilton.com.ng/pages/freshPlayer.html*"
zone_name = "frithhilton.com.ng"
